# Security definitions for trading
securities:
  # Cryptocurrencies
  BTC-USD:
    type: crypto
    exchange: binance
    base_currency: USD
    min_trade_size: 0.001
    max_trade_size: 1.0
    data_source: yfinance

  # Stocks
  AAPL:
    type: stock
    exchange: NASDAQ
    base_currency: USD
    min_trade_size: 1
    max_trade_size: 100
    data_source: yfinance

  # Add more securities as needed
  # Example:
  # MSFT:
  #   type: stock
  #   exchange: NASDAQ
  #   base_currency: USD
  #   min_trade_size: 1
  #   max_trade_size: 100
  #   data_source: yfinance 