# Strategy configuration
strategy:
  name: "FQ Trading Strategy"
  version: "1.0.0"

# Trading parameters
trading:
  position_size: 0.1  # Percentage of portfolio per trade
  max_positions: 5    # Maximum number of concurrent positions
  stop_loss: 0.02     # Stop loss percentage
  take_profit: 0.05   # Take profit percentage

# Feature selection
feature_selection:
  correlation_threshold: 0.85  # Maximum allowed correlation between features
  mutual_info_threshold: 0.01  # Minimum mutual information score to keep a feature
  boruta_max_iter: 100        # Maximum iterations for Boruta algorithm
  data_split:
    train_ratio: 0.7          # Training set ratio
    val_ratio: 0.15           # Validation set ratio
    test_ratio: 0.15          # Test set ratio
    random_state: 42          # Random seed for reproducibility
  sequence:
    length: 15                # Length of input sequences for time series
    stride: 1                 # Number of time steps to move forward for each sequence
    sampling_rate: 1          # Sample every nth time step
  clustering:
    num_clusters: -1          # Number of clusters for K-Means (-1 to disable)
    random_state: 42          # Random seed for clustering
    max_iter: 300            # Maximum iterations for K-Means
    n_init: 10               # Number of times K-Means will run with different centroid seeds

# Technical indicators
indicators:
  sma:
    short_period: 20
    long_period: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9

# Backtesting parameters
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  commission: 0.001  # 0.1% per trade

# Risk management
risk:
  max_drawdown: 0.15  # Maximum allowed drawdown
  max_daily_loss: 0.02  # Maximum daily loss
  max_position_risk: 0.01  # Maximum risk per position

# Reporting
reporting:
  generate_daily_report: true
  generate_weekly_report: true
  generate_monthly_report: true
  save_trades: true
  save_positions: true
  plot_performance: true 